[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
